### ISSUE TITLE
Sentry no longer shows variables in stack trace after switching from SDK raven-php 0.14.0.dev0 to SDK sentry-php 1.2.0

### ISSUE THREAD

**Issue by archon810** [getsentry/sentry-php#354]
Hi @dcramer, rather than continuing in Zendesk, I thought I'd fire up a public ticket here instead.

We just switched from SDK raven-php 0.14.0.dev0 to SDK sentry-php 1.2.0 and stopped seeing variables. What could be going wrong, why may they not be showing?

Here's an example of the full entry in Sentry: http://i.imgur.com/hj7yo8w.png. 

For instance, it should be trivial to debug what $target mkdir is trying to create, but the variables are just not showing.

We're on PHP Version 5.6.25 btw.

**Comment by dcramer** [comment]
@archon810 thanks! Definitely easier for us to track here. I haven't yet had a chance to look into what could be causing it -- we have test cases that show reflection working, so it's possible this is another change (e.g. misshaped data that got discarded).

**Comment by dcramer** [comment]
So one of the interesting bits of this example is its a single frame. I'm not entirely sure how that can possibly be true here unless it's all inline code (and I dont think thats the case). That said, I have a local case, and while its not the same, I do see missing arguments from mkdir.

**Comment by dcramer** [comment]
@archon810 so from what I can tell we aren't able to actually get scoped context for mkdir. I'm still digging into it, but I have a feeling this never worked for that specific kind of call.

**Comment by dcramer** [comment]
Digging through this I think we should eliminate some of the complexity of this code. We try to shift context around so the vars appear in the frame that is calling them (we effectively shift all vars up one). 

I **did** confirm that the mkdir call doesn't give us context:

```
array(4) {
  ["type"]=>
  int(2)
  ["message"]=>
  string(34) "mkdir(): No such file or directory"
  ["file"]=>
  string(74) "/Users/dcramer/Development/sentry-php/test/Raven/Tests/IntegrationTest.php"
  ["line"]=>
  int(52)
}
```

**Comment by dcramer** [comment]
@archon810 so I can't find any actual regression. Do you have an example of an error that used to have context and doesnt now? If you have a sentry.io link you can email it to me (david@).

**Comment by SeBsZ** [comment]
@dcramer , I'm noticing a possible pattern when I was trying to find errors with context for you. Could this be related to the suppressed errors bug? It seems the errors/notices without context actually had an @ in front. I can actually confirm that I'm seeing all variables in 1.2.0 in PHP exceptions that do not have the suppressor.

So to us, this felt like a 0.14.0.dev0 to 1.2.0 bug, but in reality it's due to the @. The @ bug resulted in us seeing many new exceptions, all without context.

I think this is solved actually.

**Comment by dcramer** [comment]
@SeBsZ ah thats very possible given that it was happening later in the process (maybe error_get_last never has context?)

I will go ahead and close this, but if you find any more details let me know.

**Comment by archon810** [comment]
Since the @ bug isn't resolved for us with 1.3.0 yet, from what I can tell, I'll wait for it to be resolved first to look at this again.
